name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - SERVER_HOST: "${{ secrets.SERVER_HOST_AI }}"
            SERVER_PID: "${{ secrets.SERVER_PID_AI }}"
            SERVER_UID: "${{ secrets.SERVER_UID }}"
            SERVER_TOKEN: "${{ secrets.SERVER_TOKEN_AI }}"
          - SERVER_HOST: "${{ secrets.SERVER_HOST_MAIN }}"
            SERVER_PID: "${{ secrets.SERVER_PID_MAIN }}"
            SERVER_UID: "${{ secrets.SERVER_UID }}"
            SERVER_TOKEN: "${{ secrets.SERVER_TOKEN_MAIN }}"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install root dependencies
      run: npm install
    - name: Install UI dependencies
      run: |
        cd packages/ui
        npm install
    - name: Start server
      run: |
        cd packages/ui/test/plugin
        npm install
        node server.js -sh ${{ matrix.environment.SERVER_HOST }} -spid ${{ matrix.environment.SERVER_PID }} -muid ${{ matrix.environment.SERVER_UID }} -st ${{ matrix.environment.SERVER_TOKEN }} &
    - name: Start chat/webpack run
      run: |
        cd packages/ui
        npx webpack --env plugin=http://localhost:3333 &
    - name: Install test dependencies and run tests
      run: |
        cd packages/ui/test/ui_test
        npm install
        npx playwright install
        npm test
    - name: Upload test results on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: failed-test-results
        path: packages/ui/test/ui_test/test-results/
